@startuml
start
repeat
  :Ввод данных пользователем;

  if ("Данные введены верно?") then (да)
    :Сохранение в БД;
    :Обновление баланса;

    if ("Выбор действия") then (Формирование отчета)
      :Формирование отчета;
      :Вывод на экран;
      break
    else (Добавление новой операции)
      :Добавление новой операции;
    endif

  else (нет)
    :Сообщение об ошибке;
  endif

repeat while (Новая операция или ошибка?)

stop
@enduml