@startuml
start

:Ввод данных пользователем;

if ("id telegram-аккаунта есть в БД?") then (да)
  :Запуск основного функционала программы;
else (нет)
  :Сохранение информации в БД (id, должность в компании);
  :Запуск основного функционала программы;
endif

stop
@enduml
